.TH CLIENT 1 "September 2026" "1.0" "User Commands"
.SH NAME
client \- test driver for libmyutils string and file utility functions
.SH SYNOPSIS
.B client
.SH DESCRIPTION
.B client
is a demonstration program that tests the custom string manipulation functions (mystrlen, mystrcpy, mystrncpy, mystrcat) and file utility functions (wordCount, mygrep) provided by the libmyutils library. It runs a series of built-in test cases and prints the results to standard output, verifying correct behavior of each function.
.SH AUTHOR
Written by Zuhhaa Naz <zuhhaanaz@gmail.com>
